config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  
  get '/users/:id/password/edit', to: 'users#password_edit', as: 'password'
  patch '/users/:id/password/edit', to: 'users#password_update', as: 'update_password'
  

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]
    get :liked, on: :collection
  end
  
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many :reviews, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :users, through: :likes

    validates :title, presence: true
    validates :description, presence: true
    
    before_validation :capitalize_title 
    
    def liked_by?(user)
        likes.find_by_user_id(user.id).present?
    end
    
    private
    def capitalize_title
        self.title.capitalize!
    end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    # Except index, show action it will check is user logged in
    before_action :authenticate_user!, except: [:index, :show]
    # before edit, update, show, destroy it will find the idea
    before_action :find_idea, only: [:edit, :update, :show, :destroy]
    # before edit, update, destroy it will check is the current user is valid to edit or update the idea
    before_action :authorize!, only: [:edit, :update, :destroy]

    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new idea_params
        @idea.user = current_user
        if @idea.save
            flash[:notice] = 'Idea Created Successfully'
            redirect_to idea_path(@idea.id)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @idea.update idea_params
            flash[:notice] = 'Idea updated Successfully'
            redirect_to idea_path(@idea.id)
        else
            render :edit
        end
    end

    def index 
        @ideas= Idea.order(created_at: :desc)
    end

    def liked 
        @ideas = current_user.liked_ideas.order('likes.created_at DESC')
    end

    def show
        @new_review = Review.new
        @reviews = @idea.reviews.order(created_at: :desc)
        @like = @idea.likes.find_by(user: current_user)
    end

    def destroy
        @idea.destroy
        redirect_to ideas_path
    end

    private
    def find_idea
        @idea=Idea.find_by id:params[:id]
        if @idea == nil
            redirect_to root_path, notice: "Idea Does Not Exist"
        end
    end

    def idea_params
        params.require(:idea).permit(:title, :description)
    end

    def authorize!
        unless can?(:crud, @idea)
            redirect_to root_path, notice: 'Not Authorized. Access Denied' 
        end
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-default navbar-dark">
<a class="navbar-brand" href="<%= root_path %>">Idea Factory</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ml-auto mt-lg-0">
    <li class="nav-item">
      <a class="nav-link" href="<%= root_path %>">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= ideas_path %>">Ideas</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_idea_path %>">New Idea</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="<%= root_path %>" id="navbarDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.full_name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", edit_user_path(current_user), class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Liked Question", liked_ideas_path , class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Are you sure you want to Sign Out?"}, class:"dropdown-item", style:"color:blue"%>
      </div>
    </li>
    <% else %>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
    </li>
    <% end %>
</div>
</ul>
</div>
</nav>
<%= flash[:notice]%>

app/views/ideas/_navigation2.html.erb
<nav class="navbar navbar-expand-lg navbar-default navbar-dark">
<a class="navbar-brand" href="<%= root_path %>">Idea Factory</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ml-auto mt-lg-0">
    <li class="nav-item">
      <a class="nav-link" href="<%= root_path %>">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= ideas_path %>">Ideas</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_idea_path %>">New Idea</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="<%= root_path %>" id="navbarDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.full_name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", edit_user_path(current_user), class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Liked Question", liked_ideas_path , class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Are you sure you want to Sign Out?"}, class:"dropdown-item", style:"color:blue"%>
      </div>
    </li>
    <% else %>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
    </li>
    <% end %>
</div>
</ul>
</div>
</nav>
<%= flash[:notice]%>

app/views/ideas/edit.html.erb
<%= render 'navigation2' %>
<br>
<div class="sign-in-form container">
  <div class="sign-in-brand"><a href="<%= root_path %>" class="logo">Idea Factory</a></div><br>
  <%= form_with model: @idea, local: true do |f|%>
  <% if @idea.errors.present?%>
  <p>
    <%= @idea.errors.full_messages.join(', ') %>
  </p>
  <% end %>
  <div class="sign-in-content">
    <h3><strong>Edit Idea</strong></h3>
    <strong><%= f.label :title, "Title"%></strong><br>
    <%= f.text_field :title, style:"width:100%;"%><br><br>
    <strong><%= f.label :description, "Description", cols:50, rows:3%></strong><br>
    <%= f.text_area :description, style:"width:100%;"%><br><br>
    <div>
      <%= f.submit "Edit Your Idea", style:"width:100%;", class:"sign-in-button"%><br>
      <p class="terms-of-use"><br>
        By creating a Idea, you agree to Idea Factory's<br>
        <strong style="color:#0000EE;">Conditions of Use</strong> and <strong style="color:#0000EE;">Privacy
        Notice</strong>.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/ideas/index.html.erb
<%= render 'navigation2'%>
<br>
<div class="container">
    <div class="row">
        <% @ideas.each do |idea| %>
        <div class="col-lg-4 py-2">
            <div class="post-card">
                <h2><%=link_to( idea.title.truncate(30, separator: " "), idea_path(idea.id)) %></h2>
                <div><%= idea.description.truncate(50, separator: " ") %></div>
                <div class="post-card-footer"><small>likes: <%= idea.likes.count %> | reviews : <%= idea.reviews.count %> | Posted <%= remove_unwanted_words time_ago_in_words(idea.created_at) %> ago </small></div>
            </div>
        </div>
        <% end %>
    </div>
</div>
</div>

app/views/ideas/liked.html.erb
<%= render 'navigation2'%>
<br>
<h1 class="liked__h1">Your Liked Questions</h1>
<div class="container">
    <div class="row">
        <% @ideas.each do |idea| %>
        <div class="col-lg-4 py-2">
            <div class="post-card">
                <h2><%=link_to( idea.title.truncate(30, separator: " "), idea_path(idea.id)) %></h2>
                <div><%= idea.description.truncate(50, separator: " ") %></div>
                <div class="post-card-footer"><small>likes: <%= idea.likes.count %> | reviews : <%= idea.reviews.count %> | Posted <%= remove_unwanted_words time_ago_in_words(idea.created_at) %> ago </small></div>
            </div>
        </div>
        <% end %>
    </div>
</div>
</div>

app/views/ideas/new.html.erb
<%= render 'navigation2'%>
<br>
<div class="sign-in-form container">
  <div class="sign-in-brand"><a href="<%= root_path %>" class="logo">Idea Factory</a></div><br>
  <%= form_with model: @idea, local: true do |f|%>
    <div class="sign-in-content">
    <h3><strong>Create Idea</strong></h3>
    <% if @idea.errors.present?%>
    <p style="color:red;">
      <%= @idea.errors.full_messages.join(', ') %>
    </p>
    <% end %>
    <strong><%= f.label :title, "Title"%></strong>
    <%= f.text_field :title, style:"width:100%;"%><br>
    <strong><%= f.label :description, "Description", cols:50, rows:3%></strong>
    <%= f.text_area :description, style:"width:100%;"%><br>
    <div>
      <%= f.submit "Create Your Idea", style:"width:100%;", class:"sign-in-button"%><br>
      <p class="terms-of-use"><br>
        By creating a Idea, you agree to Idea Factory's<br>
        <strong style="color:#0000EE;">Conditions of Use</strong> and <strong style="color:#0000EE;">Privacy
        Notice</strong>.</p>
        
      <% end %>
    </div>
  </div>
</div>

app/views/ideas/show.html.erb
<nav class="navbar navbar-expand-lg navbar-default navbar-dark">
<a class="navbar-brand" href="<%= root_path %>">Idea Factory</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ml-auto mt-lg-0">
    <li class="nav-item">
      <a class="nav-link" href="<%= root_path %>">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= ideas_path %>">Ideas</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_idea_path %>">New Idea</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="<%= root_path %>" id="navbarDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.full_name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", edit_user_path(current_user), class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Liked Question", liked_ideas_path , class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Are you sure you want to Sign Out?"}, class:"dropdown-item", style:"color:blue"%>
      </div>
    </li>
    <% else %>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
    </li>
    <% end %>
</div>
</ul>
</div>
</nav>
<%= flash[:notice]%>

<div class="show-post-container">
  <br>
  <small class="path">Home > Ideas > <%= @idea.title %></small>
  <div class="show-post p-3">
    <%= image_tag "bmo.jpg", alt: "bmo image", class:"post-image", style:"width:40%; height:auto;"%>
    <div class="post-header">
      <div class"post-flex">
        <h1 class="post-header1"><%= @idea.title %>
          <% if @like.present? && can?(:destroy, @like) %>
          <%=link_to(
                "[Unlike]",
                like_path(@like),
                method: :delete
            )%>
          <% elsif can?(:like, @idea) %>
          <%=link_to(
                "[Like]",
                idea_likes_path(@idea),
                method: :post
            )%>
          <% end %>
        </h1>

        <small style="color:black;">by <strong
            style="color:#0000EE;"><%= @idea.user&.full_name || 'DELETED' %></strong></small><br>
        <small style="color:black;">Posted on
          <strong style="color:#0000EE;"><%= @idea.created_at.strftime("%b %d, %Y") %> |
            <%= pluralize(@idea.reviews.count, "review") %> | <%= pluralize(@idea.likes.count, "like") %>
          </strong></small>
        <% if can? :crud, @idea %>
        <div class="post-buttons">
          <%= link_to 'Edit Idea', edit_idea_path(@idea.id), class: "edit-button"%>
          <%= link_to("Delete Idea", idea_path(@idea), method: :delete, data:{confirm:'Are you sure?'}, class: "delete-button") %>
        </div>
        <% end %>
      </div>
      <p class="post-body"><%= @idea.description %></p>
    </div>
  </div>
  <hr class="post-hr">
  <section>
    <%= form_with(model: [@idea, @new_review], local: true) do |f| %>
    <h4 class="comment-header"><strong>Review this Idea</strong></h4>
    <% if @new_review.errors.present? %>
    <p class="form-errors">
      <%= @new_review.errors.full_messages.join(", ") %>
    </p>
    <% end %>
    <div class="form-group">
      <%= f.text_area(
            :body,
            cols: 50,
            rows: 3,
            placeholder:"What are your thoughts?",
            class: "form-control"
        ) %>
    </div>

    <%= f.submit 'Write a user review', class: "comment-button"%>
    <% end %>

    <hr class="board">
    <div class="comment">
      <% @reviews.each do |review| %>
      <div class="comment-head">
        <%= image_tag "unknown", alt: "user picture", class:"unknown-image", style:"width:3%; height:auto;"%>
        <div class="image-user">
          <strong>&nbsp;&nbsp;<%= review.user&.full_name || 'DELETED' %> </strong>
        </div>
      </div>
      <small>Reviewed in <%= review.created_at.strftime("%b %d, %Y") %></small>
      <div class="comment-body">
        <%= review.body %> <br>
      </div>
      <small>
        <% if can? :crud, review %>
        <%= link_to 'Delete', idea_review_path(@idea, review), method: :delete, data: { confirm: 'Are you sure that you want to delete this review?' } %>
        <% end %>
      </small>
      <% end %>
    </div>
  </section>
  <br>