config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  
  get '/users/:id/password/edit', to: 'users#password_edit', as: 'password'
  patch '/users/:id/password/edit', to: 'users#password_update', as: 'update_password'
  

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]
    get :liked, on: :collection
  end
  
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify

    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :likes, source: :idea



    # check is email is given and it is unique
    validates :email, presence: true, uniqueness: true,
    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    # Adds attribute accessors to the user model for password and password_confirmation
    # Validates presence of password and password matching with password_confirmation if present
    # Encrypts the password and stores it in password_digest using the bcrypt gem
    has_secure_password


    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:new, :create]
    before_action :find_user, only: [:edit, :update, :destroy, :password_edit, :password_update]
    
    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
        if @user.id != session[:user_id]
            redirect_to root_path, notice: "Not Aurthorized, Access Denied!"
        end
    end

    def update
        if @user.id != session[:user_id]
            redirect_to root_path, notice: "Not Aurthorized, Access Denied!"
        else
            if @user.update user_params
                redirect_to edit_user_path, notice: "User Information Updated Succesfully"
            else
                flash[:alert] = "Oops! Update failed try again"
                render :edit
            end
        end
    end

    def password_edit
        if @user.id != session[:user_id]
            redirect_to root_path, notice: "Not Aurthorized, Access Denied!"
        end
    end

    def password_update
        if @user.id != session[:user_id]
            redirect_to root_path, notice: "Not Aurthorized, Access Denied!"
        else
            if @user&.authenticate params[:user][:current_password]
                if params[:user][:new_password] == params[:user][:new_password_confirmation]
                    if @user.update password: params[:user][:new_password], password_confirmation: params[:user][:new_password_confirmation]
                        session[:user_id] = nil
                        redirect_to root_path, notice: "Password has been changed successfully. Plase Log-in Again"
                    else
                        flash[:alert] = "Ooops! Password update failed. Try again"
                        render :password_edit
                    end
                else
                    flash[:alert] = "Password again does not match"
                    render :password_edit, notice: "Password again does not match"
                end
            else
                flash[:alert] = "Current Password is wrong"
                render :password_edit
            end
        end
    end

    def destroy
        session[:user_id] = nil
        @user.destroy
        redirect_to root_path
    end

    private
    def user_params
        params.require(:user).permit(
            :first_name, :last_name, :email, :password, :password_confirmation
        )
    end

    def find_user
        @user=User.find_by id:params[:id]
        if @user == nil
            redirect_to root_path, notice: "User Id Does Not Exist"
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br>
<div class="sign-in-form container">
    <div class="sign-in-brand">
        <a href="<%= root_path %>" class="logo">Idea Factory</a>
    </div><br>
    <%= form_with model: @user, local: true do |f|%>
    <div class="sign-in-content">
        <h3><strong>My Profile</strong></h3>
        <% if @user.errors.any?%>
        <p style="color:red;">
            <%= @user.errors.full_messages.join(', ') %>
        </p>
        <% end %>
        <p><%= flash[:notice] || flash[:alert] || flash[:success]%></p>
        <strong><%= f.label :first_name, "First name"%></strong>
        <%= f.text_field :first_name, style:"width:100%;"%>
        <strong><%= f.label :last_name, "Last name"%></strong>
        <%= f.text_field :last_name, style:"width:100%;"%>
        <strong><%= f.label :email, "Email"%></strong>
        <%= f.email_field :email, style:"width:100%;"%>
        <div><br>
            <%= f.submit "Update Your Profile", style:"width:100%;", class:"sign-in-button"%><br>
            <a button type="button" class="delete-acc-button" href="<%= password_path(@user)%>"
            style="margin-top:1em;">Change
            Password</a></button>
            <p class="terms-of-use"><br>
                By deleing an account, you will be no longer to access<br>
                <strong style="color:#0000EE;">Conditions of Use</strong> and <strong style="color:#0000EE;">Privacy
                    Notice</strong>.
            </p>
            <%= link_to "Delete Account", user_path(current_user), method: :delete, data: {confirm: "Are you sure you want to Delete Account?"}, class:"sign-up-button", type:"button"%>
            <% end %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<br>
<div class="sign-in-form container">
    <div class="sign-in-brand">
        <a href="<%= root_path %>" class="logo">Idea Factory</a>
    </div><br>
    <%= form_with model: @user, local: true do |f|%>
    <div class="sign-in-content">
        <h3><strong>Create Account</strong></h3>
        <% if @user.errors.any? %>
        <ul style="color:red;">
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        <% end %>

        <strong><%= f.label :first_name, "First name"%></strong>
        <%= f.text_field :first_name, style:"width:100%;"%>
        <strong><%= f.label :last_name, "Last name"%></strong>
        <%= f.text_field :last_name, style:"width:100%;"%>
        <strong><%= f.label :email, "Email"%></strong>
        <%= f.email_field :email, style:"width:100%;"%>
        <strong><%= f.label :password, "Password"%></strong>
        <%= f.password_field :password, style:"width:100%;"%>
        <strong><%= f.label :password_confirmation, "Password again" %></strong><br>
        <%= f.password_field :password_confirmation, style:"width:100%;"%>
        <div><br>
            <%= f.submit "Create Your Account", style:"width:100%;", class:"sign-in-button"%><br>
            <p class="terms-of-use"><br>
                By creating an account, you agree to Idea Factory's<br>
                <strong style="color:#0000EE;">Conditions of Use</strong> and <strong style="color:#0000EE;">Privacy
                    Notice</strong>.
                <hr>
                <p><strong>Already have account? <a href="<%= new_session_path %>">Sign In</a></strong></p>
                <% end %>
        </div>
    </div>

app/views/users/password_edit.html.erb
<br>
<div class="sign-in-form container">
    <div class="sign-in-brand">
        <a href="<%= root_path %>" class="logo">Idea Factory</a>
    </div><br>
    <%= form_with model: @user, url: update_password_path(@user), local: true do |f|%>
    <div class="sign-in-content">
        <h3><strong>My Profile</strong></h3>
        <% if @user.errors.any?%>
        <p style="color:red;">
            <%= @user.errors.full_messages.join(', ') %>
        </p>
        <% end %>
        <p><%= flash[:notice] || flash[:alert] || flash[:success]%></p>

        <strong><%= f.label :current_password, "Current Password"%></strong>
        <%= f.password_field :current_password, style:"width:100%;"%>
        <strong><%= f.label :new_password, "New Password"%></strong>
        <%= f.password_field :new_password, style:"width:100%;"%>
        <strong><%= f.label :new_password_confirmation, "New Password again" %></strong><br>
        <%= f.password_field :new_password_confirmation, style:"width:100%;"%>
        <div><br>
            <%= f.submit "Change Password", style:"width:100%;", class:"sign-in-button"%><br>
            <% end %>
        </div>
    </div>
</div>