config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  
  get '/users/:id/password/edit', to: 'users#password_edit', as: 'password'
  patch '/users/:id/password/edit', to: 'users#password_update', as: 'update_password'
  

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]
    get :liked, on: :collection
  end
  
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_navigation.html.erb
<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-faded">
<a class="navbar-brand" href="<%= root_path %>">Idea Factory</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ml-auto mt-lg-0">
    <li class="nav-item">
      <a class="nav-link" href="<%= root_path %>">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= ideas_path %>">Ideas</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_idea_path %>">New Idea</a>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="<%= root_path %>" id="navbarDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.full_name %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", edit_user_path(current_user), class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Liked Question", liked_ideas_path , class:"dropdown-item", style:"color:blue" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Are you sure you want to Sign Out?"}, class:"dropdown-item", style:"color:blue"%>
      </div>
    </li>
    <% else %>
    <li class="nav-item">
      <a class="nav-link" href="<%= new_session_path %>">Sign In</a>
    </li>
    <% end %>
</div>
</ul>
</div>
</nav>
<%= flash[:notice]%>

app/views/welcome/home.html.erb
<% if user_signed_in? %>
<div class="fullwidth2">
    <%= render 'navigation' %>
    <h1 class="welcome__h1"><strong>Money.log</strong></h1>
    <p class="welcome__p"><strong>"Drop by Drop fills the tub."</strong></p>
    <% else %>
    <div class="fullwidth">
        <h1 class="welcome__h1"><strong>Money.log()</strong></h1>
        <p class="welcome__p"><strong>"Dreams Do Come True"</strong></p>
        <a button type="button" class="welcome__button" href="<%= new_session_path %>">Start</a></button>
    </div>

    <% end %>